name: CICD

on:
  push:
    branches: [ main ]

jobs:
  generate-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   
    
    - name: Github Tag Bump
      id: tab_bump
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
        INITIAL_VERSION: 1.0.2
        DEFAULT_BUMP: patch
        
    outputs:
      new_version: ${{ steps.tab_bump.outputs.new_tag }}
   
  build-and-deploy-service:

    runs-on: ubuntu-latest
    needs: generate-version
    
    env: 
      ACR_APP_NAME: acrplayeconomy
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and push Docker image
   
      uses: docker/build-push-action@v3.0.0
      with:
        secrets: |
          "GH_OWNER=${{github.repository_owner}} "
          "GH_PAT=${{secrets.GH_PAT}} "
        tags: ${{env.ACR_APP_NAME}}.azurecr.io/play.trading:${{ needs.generate-version.outputs.new_version }}
